### ISSUE TITLE
Bring back the test to check adding an extension to My Favorites

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#836]
In https://github.com/mozilla/Addon-Tests/pull/835, we removed the test to check if adding an extension to Favorites works.

This test needs to be brought back with the following updated steps:
1. Log in to AMO
2. Hover on the profile name; Click on My Favorites
3. Click on Edit Collection
4. In the Edit form, switch to Add-ons tab
5. Add an extension and save changes
6. Check that the add-on is now listed in the My Favorites Collection and the heart icon is red

**Comment by stephendonner** [comment]
Heya @stupchiy - would you be up for taking this?  Thanks either way :-)

**Comment by stupchiy** [comment]
Hey @stephendonner, sure. 

One small questions @krupa : 

> 2. Hover on the profile name; Click on My Favorites

The "My Favorites" link is appearing only after you have at least one add-on in that collection, is it supposed to be like that?

**Comment by krupa** [comment]
Yes, that is correct.  I guess we can navigate directly to the Favorites collection page.

**Comment by stupchiy** [comment]
Hey @stephendonner , @krupa, I've made a pull request #837, but it is currently failing, because of weird behavior when you add and save add-ons into your Favorites collection. Spent a lot of time on investigating, but haven't found any sequence. Like sometimes it does not appear in 'My Favorites' right away after save, only after some time and sometimes some old saved addons appear in the same list. Please advice how to proceed further.
