### ISSUE TITLE
Fix test: TestReviews.test_that_new_review_is_saved

### ISSUE THREAD

**Issue by krupa** [mozilla/Addon-Tests#844]
TestReviews.test_that_new_review_is_saved has been failing for a while now and we need to look into making this test more robust.

**Comment by davehunt** [comment]
I believe this is a genuine issue. This test creates a new review and checks the rating, author, date, and text of the review. Before 143708cc73bc8b21a215666c3161438a2ab5b152 we used the same author for all reviews, but we had intermittent failures when the date mismatched. We concluded this was due to the timezone, but it may have been that the review was intermittently not being displayed. We now have frequent failures because the author is unique every time we run the test, highlighting that reviews are often not displayed within the expectations of the test. We only have automated results going back to February 29th, so I'm unable to determine when this test became intermittent.

**Comment by davehunt** [comment]
I'm going to raise an issue and xfail this test, but we might need to modify it if the test is expecting the review to be displayed in an unreasonably short amount of time.

**Comment by davehunt** [comment]
See #848 for xfail. I'm going to unassign myself from this now as we really need input on the associated addons-server issue before we can proceed.

**Comment by davehunt** [comment]
This is now passing. @stupchiy mind removing the xfail for us?

**Comment by davehunt** [comment]
@justinpotts mind taking the removal of the xfail?
